### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by Nyholm** [NobletSolutions/JMSTranslationBundle#4]
There are some new maintainers on JMSTranslationBundle. Myself, @gnat42 and @gouaille do now have push access. 

I've seen your ns-master branch and we will try to merge the same PRs to our master. We will not do a PR of all your changes because we believe in small changes. But we are inspired by your work. 

This is just a FYI but I would be happy if you could help us in this work.

**Comment by gnat42** [comment]
Hey @Nyholm  yeah I'm @gnat42. :) I'll close my fork soon once I can use the upstream again.

**Comment by Nyholm** [comment]
=)
